[0m11:37:44.017527 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f76968e41f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7695083910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7695083ac0>]}


============================== 11:37:44.019837 | 49aeed65-4691-4156-a8e7-b1045abf7867 ==============================
[0m11:37:44.019837 [info ] [MainThread]: Running with dbt=1.8.7
[0m11:37:44.020467 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/aman/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init my_project', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:37:44.034366 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/home/aman/.dbt')}
[0m11:37:44.034947 [info ] [MainThread]: Creating dbt configuration folder at 
[0m11:37:44.036479 [debug] [MainThread]: Starter project path: /home/aman/Documents/10Academy/week7/venv/lib/python3.10/site-packages/dbt/include/starter_project
[0m11:37:44.038685 [info ] [MainThread]: 
Your new dbt project "my_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:37:44.039163 [info ] [MainThread]: Setting up your profile.
[0m11:37:44.039889 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m11:37:44.040717 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 0.07109786, "process_user_time": 1.135945, "process_kernel_time": 0.048167, "process_mem_max_rss": "86152", "process_in_blocks": "320", "process_out_blocks": "64", "command_success": false}
[0m11:37:44.041339 [debug] [MainThread]: Command `dbt init` failed at 11:37:44.041225 after 0.07 seconds
[0m11:37:44.041780 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f76968e41f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7696c18310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7696c18100>]}
[0m11:37:44.042238 [debug] [MainThread]: Flushing usage events
[0m11:37:54.540000 [debug] [MainThread]: Error sending anonymous usage statistics. Disabling tracking for this execution. If you wish to permanently disable tracking, see: https://docs.getdbt.com/reference/global-configs#send-anonymous-usage-stats.
[0m11:39:10.095948 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1ca7dfc1f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1ca776e560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1ca80e6710>]}


============================== 11:39:10.098114 | d0526855-0da9-4c5a-bfc3-3de8c2fc6e65 ==============================
[0m11:39:10.098114 [info ] [MainThread]: Running with dbt=1.8.7
[0m11:39:10.098834 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/aman/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:39:10.099392 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/aman/Documents/10Academy/week7/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:39:10.100170 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.051908128, "process_user_time": 1.122605, "process_kernel_time": 0.03995, "process_mem_max_rss": "85776", "process_out_blocks": "16", "command_success": false, "process_in_blocks": "0"}
[0m11:39:10.100709 [debug] [MainThread]: Command `dbt run` failed at 11:39:10.100620 after 0.05 seconds
[0m11:39:10.101101 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1ca7dfc1f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1ca80e7a90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1ca80e76d0>]}
[0m11:39:10.101499 [debug] [MainThread]: Flushing usage events
[0m11:41:50.648860 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba3e9d4190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba3ed2b0d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba3ed2b070>]}


============================== 11:41:50.651013 | 5de3455f-ac61-4e0c-945b-9b64f20df48c ==============================
[0m11:41:50.651013 [info ] [MainThread]: Running with dbt=1.8.7
[0m11:41:50.651736 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/aman/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m11:41:50.652241 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/aman/Documents/10Academy/week7/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:41:50.652944 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.05036061, "process_user_time": 1.324732, "process_kernel_time": 0.047881, "process_mem_max_rss": "85680", "process_in_blocks": "24", "process_out_blocks": "8", "command_success": false}
[0m11:41:50.653506 [debug] [MainThread]: Command `dbt run` failed at 11:41:50.653419 after 0.05 seconds
[0m11:41:50.653891 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba3e9d4190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba3ed2a770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba3ed2b5b0>]}
[0m11:41:50.654317 [debug] [MainThread]: Flushing usage events
[0m20:21:03.505342 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f13dba40250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f13dab9af80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f13dbd23d90>]}


============================== 20:21:03.513113 | 0f88e3d2-36a0-4163-806f-eb675e01e78d ==============================
[0m20:21:03.513113 [info ] [MainThread]: Running with dbt=1.8.7
[0m20:21:03.514616 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/home/aman/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt test', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m20:21:03.515762 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/aman/Documents/10Academy/week7/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:21:03.517283 [debug] [MainThread]: Resource report: {"command_name": "test", "command_wall_clock_time": 0.12846272, "process_user_time": 2.790474, "process_kernel_time": 0.165092, "process_mem_max_rss": "85592", "process_in_blocks": "33744", "process_out_blocks": "8", "command_success": false}
[0m20:21:03.518427 [debug] [MainThread]: Command `dbt test` failed at 20:21:03.518213 after 0.13 seconds
[0m20:21:03.519400 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f13dba40250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f13db36bac0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f13db36bcd0>]}
[0m20:21:03.520789 [debug] [MainThread]: Flushing usage events
